/*
 * Auto-generated ESP32 code
 * Generated by Atech Hardware Platform
 * Using athera module drivers with FreeRTOS tasks
 */

// ========== INCLUDES ==========
#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_task_wdt.h"
#include "esp_system.h"
#include <Preferences.h>
#include "modules/shared/atech_helpers.h"
#include "modules/shared/atech_ui.h"
#include "modules/connectivity/serial_templates.h"
#include <Wire.h>
#include <i2c_interface.h>
#include <i2c_hardware.h>
#include <i2c_software.h>
#include "modules/audio/speaker.h"
#include "modules/distance/vl53l5cx.h"
#include "modules/led/neopixel.h"
#include "modules/input/button.h"
// EMBEDDED_SOUNDS_FP: none
#include <ArduinoJson.h>

// ========== FREERTOS TASK HANDLES ==========
TaskHandle_t mainTaskHandle = NULL;

// ========== GLOBAL VARIABLES ==========
// ========== USB-SERIAL TRANSPORT ==========
AtechSerial wifi(115200);

// ========== I2C INTERFACES ==========
// Hardware I2C buses (clock set per-bus in setup; see begin())
WireI2C i2c_port_7(Wire, 6, 7);

// ========== MODULE INSTANCES ==========
// I2S Speaker (MAX98357A)
// Pins swapped for left-side placement: port_2 pins first, port_1 pins second
Speaker speaker_1(4, 5, 8);
// VL53L5CX 8x8 Distance Sensor
VL53L5CX_Sensor vl53l5cx_1(Wire);
// NeoPixel 3x3 LED Grid
NeoPixelGrid neopixel_1(40, 41);
// Button
ButtonModule button_1(17, true);


// User behavior variables and helper functions
// State variables
bool lightOn = false;
int16_t currentDist = 0;
unsigned long lastSensorPost = 0;
unsigned long lastToneTime = 0;
const int TONE_INTERVAL_MS = 300;
float lastPlayedFreq = 0.0f;
// Distance thresholds (mm) for a tighter 0–200 mm control range.
const int16_t MAX_DISTANCE_MM = 200;
const int16_t CENTER_DISTANCE_MM = 100;
const int16_t NEAR_THRESH  = 70;    // < 70mm    → low pitch
const int16_t MID_THRESH   = 100;   // 70–100mm  → mid pitch
const int16_t FAR_THRESH   = 150;   // 100–150mm → high pitch
                                     // > 150mm   → very high / alarm
// LED color when light is ON
const uint8_t LIGHT_R = 255, LIGHT_G = 200, LIGHT_B = 80; // warm white
// Color for distance feedback on LEDs
void setLedForDistance(int16_t dist) {
  if (!lightOn) return;
  if (dist > 32000) {
    // sentinel — nothing detected, cool blue pulse
    neopixel_1.setAll(0, 30, 80);
  } else if (dist < NEAR_THRESH) {
    neopixel_1.setAll(0, 180, 0);      // green — close
  } else if (dist < MID_THRESH) {
    neopixel_1.setAll(200, 150, 0);    // amber — mid
  } else if (dist < FAR_THRESH) {
    neopixel_1.setAll(220, 60, 0);     // orange — far
  } else {
    neopixel_1.setAll(180, 0, 0);      // red — very far / alarm
  }
  neopixel_1.show();
}
// Choose note frequency based on distance
float distToFreq(int16_t dist) {
  if (dist < 0) dist = 0;
  float clamped = (float)dist;
  if (clamped > MAX_DISTANCE_MM) clamped = MAX_DISTANCE_MM;
  // Map 0–200mm to 0–72 semitones above C2 (65.41 Hz)
  float semitones = (clamped / (float)MAX_DISTANCE_MM) * 72.0f;
  float freq = 65.41f * powf(2.0f, semitones / 12.0f);
  return freq;
}
void handleMessage(const char* action, const char* value) {
  if (strcmp(action, "set_color") == 0) {
    StaticJsonDocument<128> doc;
    if (deserializeJson(doc, value)) return;
    if (!doc.is<JsonObject>()) return;
    int r = doc["r"] | 0;
    int g = doc["g"] | 0;
    int b = doc["b"] | 0;
    if (r < 0 || r > 255 || g < 0 || g > 255 || b < 0 || b > 255) return;
    neopixel_1.setAll(r, g, b);
    neopixel_1.show();
  } else if (strcmp(action, "brightness") == 0) {
    int bri = atoi(value);
    if (bri < 0 || bri > 255) return;
    neopixel_1.setBrightness(bri);
    neopixel_1.setAll(LIGHT_R, LIGHT_G, LIGHT_B);
    neopixel_1.show();
  } else if (strcmp(action, "clear") == 0) {
    lightOn = false;
    neopixel_1.clear();
    neopixel_1.show();
  } else if (strcmp(action, "speaker_stop") == 0) {
    // Audio is handled by the laptop/browser instead of the board speaker.
  } else if (strcmp(action, "play_tone") == 0) {
    // Ignore tone requests; the browser provides the game audio.
  }
}

// ========== MAIN TASK (runs on Core 1) ==========
void mainTask(void* parameter) {
  esp_task_wdt_add(NULL);  // Subscribe to task watchdog (30s timeout)
  uint32_t _lastHeapLog = 0;
  // Task runs forever
  while (true) {
    esp_task_wdt_reset();
    uint32_t _nowMs = millis();
    if (_nowMs - _lastHeapLog > 30000) {
      _lastHeapLog = _nowMs;
      Serial.printf("[Atech heap] free=%u min=%u\n", (unsigned)ESP.getFreeHeap(), (unsigned)ESP.getMinFreeHeap());
    }
        // ========== USER BEHAVIOR ==========
        wifi.maintain();
        button_1.update();

        // --- Button toggles running/stopped state ---
        if (button_1.wasPressed()) {
        lightOn = !lightOn;
        if (lightOn) {
        wifi.postButtonEvent("button_press", 1);
        } else {
        wifi.postButtonEvent("button_press", 0);
        }
        }

        // --- Refresh LED every loop based on state ---
        neopixel_1.setBrightness(30);
        if (lightOn) {
        neopixel_1.setAll(0, 180, 0);
        } else {
        neopixel_1.setAll(180, 0, 0);
        }
        neopixel_1.show();

        // --- Read distance sensor ---
        if (vl53l5cx_1.isReady()) {
        currentDist = vl53l5cx_1.getMinDistance();
        }

        // --- Distance sensor still reports values for the website to use ---
        // Audio is played by the laptop/browser instead of the board speaker.

        // --- Post sensor event max once per second ---
        if (millis() - lastSensorPost >= 1000) {
        lastSensorPost = millis();
        if (currentDist < 32767) {
        wifi.postSensorEventInt("min_distance", (int)currentDist, "vl53l5cx_distance");
        }
        }

        // ========== TASK DELAY ==========
        vTaskDelay(pdMS_TO_TICKS(20));
  }
}

// ========== SETUP ==========
void setup() {
  Serial.setRxBufferSize(8192);
  Serial.begin(115200);
  Serial.setTxTimeoutMs(0);
  Serial.println("Initializing...");

  // ========== BOOT DIAGNOSTICS ==========
  {
    Preferences _bootPrefs;
    _bootPrefs.begin("atech_boot", false);
    uint32_t _bootCount = _bootPrefs.getUInt("count", 0) + 1;
    _bootPrefs.putUInt("count", _bootCount);
    _bootPrefs.end();

    esp_reset_reason_t _reason = esp_reset_reason();
    const char* _reasonStr = "UNKNOWN";
    switch (_reason) {
      case ESP_RST_POWERON:   _reasonStr = "POWERON";   break;
      case ESP_RST_EXT:       _reasonStr = "EXT_PIN";   break;
      case ESP_RST_SW:        _reasonStr = "SOFTWARE";  break;
      case ESP_RST_PANIC:     _reasonStr = "PANIC";     break;
      case ESP_RST_INT_WDT:   _reasonStr = "INT_WDT";   break;
      case ESP_RST_TASK_WDT:  _reasonStr = "TASK_WDT";  break;
      case ESP_RST_WDT:       _reasonStr = "OTHER_WDT"; break;
      case ESP_RST_DEEPSLEEP: _reasonStr = "DEEPSLEEP"; break;
      case ESP_RST_BROWNOUT:  _reasonStr = "BROWNOUT";  break;
      case ESP_RST_SDIO:      _reasonStr = "SDIO";      break;
      default: break;
    }

    Serial.println();
    Serial.println("================ ATECH BOOT ================");
    Serial.printf("  Boot count : %u\n", _bootCount);
    Serial.printf("  Reset cause: %s (%d)\n", _reasonStr, (int)_reason);
    Serial.printf("  Free heap  : %u bytes\n", (unsigned)ESP.getFreeHeap());
    Serial.printf("  Min heap   : %u bytes (lowest since boot)\n", (unsigned)ESP.getMinFreeHeap());
    Serial.printf("  CPU freq   : %u MHz\n", (unsigned)ESP.getCpuFreqMHz());
    Serial.println("============================================");
  }

  // Initialize I2C interfaces
  i2c_port_7.begin(400000);  // Hardware I2C at 400kHz

  // Initialize modules
  speaker_1.begin();
  if (!vl53l5cx_1.begin()) {
    Serial.println("Failed to initialize VL53L5CX 8x8 Distance Sensor");
  }
  neopixel_1.begin();
  delay(10);  // Allow LED strip to stabilize
  button_1.begin();

  // ========== USB-SERIAL TRANSPORT ==========
  wifi.connect();  // Serial.begin(115200) — always succeeds
  Serial.println("[Atech] Transport: USB-Serial");

  Serial.println("Setup complete!");

  // ========== USER BEHAVIOR SETUP ==========
  speaker_1.setVolume(2.0f);
  neopixel_1.setBrightness(30);
  neopixel_1.setAll(180, 0, 0);
  neopixel_1.show();
  wifi.onMessage(handleMessage);
  // Brief startup chime
  speaker_1.playNote(NOTE_E5, 70);
  speaker_1.playNote(NOTE_G5, 110);

  // ========== TASK WATCHDOG ==========
  esp_task_wdt_init(30, true);  // 30s timeout, panic on trigger

  // ========== CREATE FREERTOS TASKS ==========
  // Create main task on Core 1 (Core 0 is used by WiFi/BT)
  xTaskCreatePinnedToCore(
    mainTask,           // Task function
    "MainTask",         // Task name
    16384,              // Stack size (bytes) - 16KB for HTTPS/TLS
    NULL,               // Parameters
    1,                  // Priority (1 = low, higher = more priority)
    &mainTaskHandle,    // Task handle
    1                   // Core ID (0 or 1)
  );

  Serial.println("FreeRTOS tasks started!");
}

// ========== MAIN LOOP (empty - tasks handle everything) ==========
void loop() {
  // Nothing here - FreeRTOS tasks handle all operations
  // This allows other tasks and system processes to run
  vTaskDelay(portMAX_DELAY);
}